package net.a.g.jbpm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StateData implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public StateData() {
    }




}